

MQTT_SERVER_IP = "188.166.233.211"
MQTT_SERVER_PORT = 1883
MQTT_SERVER_KEEPALIVE = 60

GLOBAL_ID_TOPIC_SEND = 'multiProtocolGateway/Demo/toMQTT/GlobalId'
GLOBAL_DESC_NODE_SEND = 'multiProtocolGateway/Demo/toMQTT/GlobalDESC'

ESP8266_REGISTER_NEW_DEVICE_TOPIC_GET = 'multiProtocolGateway/Demo/fromMQTT/ESP8266/registerNewDevice'
ESP8266_CMD_FROM_CORE_TO_NODE_SEND = 'multiProtocolGateway/Demo/toMQTT/ESP8266/CMD' #+ChipID
ESP8266_REPORT_FROM_NODE_TO_CORE_GET = 'multiProtocolGateway/Demo/toMQTT/ESP8266/REPORT'




